# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM luigidifraia/datacube-notebook:v1.1.2-alpha
ENV TAG="v1.1.2-alpha"
COPY binder/README.ipynb .
